---
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - name: Install dependencies
        run: |
          npm i -f
          cd client && npm i -f && cd ..
      - name: Format
        run: |
          npm run format
      - name: Generate proto
        run: |
          npm run rpc:gen
      - name: Build and publish client
        run: |
          cp -r ./gen ./client
          cd client && npm run build && npm publish && cd ..
      # - name: Generate documentation
      #   run: |
      #     npm run gen
      # TODO: Figure out how to generate documentation
