---
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Format
        uses: borales/actions-yarn@v4
        with:
          cmd: format
      - name: Generate proto
        uses: borales/actions-yarn@v4
        with:
          cmd: rpc:gen
      - name: Copy proto files
        run: |
          cp -r ./gen ./client
      - name: Install dependencies for client
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: 'client'
      - name: Build client
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: 'client'
